SCREEN_WIDTH = 800
SCREEN_HEIGTH = 600
FPS = 60

WINDOW_TITLE = "The Epic Feat Of Octavio Mesa"

COLOR_BG = (10,10,15)

TILE_SIZE = 32
MAP_WIDTH_TILES = 50
MAP_HEIGHT_TILES = 50

MAP_WIDTH_PX = TILE_SIZE * MAP_WIDTH_TILES
MAP_HEIGHT_PX = TILE_SIZE * MAP_HEIGHT_TILES

PLAYER_MAX_HEALTH = 100
ENEMY_BASE_HEALTH = 30
